# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir H:/Xilinxprojects/project_iptest/project_iptest.cache/wt [current_project]
set_property parent.project_path H:/Xilinxprojects/project_iptest/project_iptest.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip -quiet h:/Xilinxprojects/project_iptest/project_iptest.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.xci
set_property is_locked true [get_files h:/Xilinxprojects/project_iptest/project_iptest.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top dds_compiler_0 -part xc7a100tcsg324-1 -mode out_of_context

rename_ref -prefix_all dds_compiler_0_

write_checkpoint -force -noxdef dds_compiler_0.dcp

catch { report_utilization -file dds_compiler_0_utilization_synth.rpt -pb dds_compiler_0_utilization_synth.pb }

if { [catch {
  file copy -force H:/Xilinxprojects/project_iptest/project_iptest.runs/dds_compiler_0_synth_1/dds_compiler_0.dcp h:/Xilinxprojects/project_iptest/project_iptest.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub h:/Xilinxprojects/project_iptest/project_iptest.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub h:/Xilinxprojects/project_iptest/project_iptest.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim h:/Xilinxprojects/project_iptest/project_iptest.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim h:/Xilinxprojects/project_iptest/project_iptest.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir H:/Xilinxprojects/project_iptest/project_iptest.ip_user_files/ip/dds_compiler_0]} {
  catch { 
    file copy -force h:/Xilinxprojects/project_iptest/project_iptest.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0_stub.v H:/Xilinxprojects/project_iptest/project_iptest.ip_user_files/ip/dds_compiler_0
  }
}

if {[file isdir H:/Xilinxprojects/project_iptest/project_iptest.ip_user_files/ip/dds_compiler_0]} {
  catch { 
    file copy -force h:/Xilinxprojects/project_iptest/project_iptest.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0_stub.vhdl H:/Xilinxprojects/project_iptest/project_iptest.ip_user_files/ip/dds_compiler_0
  }
}
