# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/project_DDS/project_DDS.cache/wt [current_project]
set_property parent.project_path H:/project_DDS/project_DDS.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  H:/project_DDS/project_DDS.srcs/sources_1/new/decoder.vhd
  {H:/Vhdl codes/pdm1.vhd}
  {H:/Vhdl codes/addrcount.vhd}
  {H:/Vhdl codes/ratecount.vhd}
  {H:/Vhdl codes/memory1.vhd}
  {H:/Vhdl codes/volume1.vhd}
  {H:/Vhdl codes/ddstop.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc H:/project_DDS/constraintsss.xdc
set_property used_in_implementation false [get_files H:/project_DDS/constraintsss.xdc]


synth_design -top dds -part xc7a100tcsg324-1


write_checkpoint -force -noxdef dds.dcp

catch { report_utilization -file dds_utilization_synth.rpt -pb dds_utilization_synth.pb }
