# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/Xilinxprojects/project_memory/project_memory.cache/wt [current_project]
set_property parent.project_path H:/Xilinxprojects/project_memory/project_memory.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib H:/Xilinxprojects/project_memory/project_memory.srcs/sources_1/new/memry_source.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top memory_01 -part xc7a100ticsg324-1L


write_checkpoint -force -noxdef memory_01.dcp

catch { report_utilization -file memory_01_utilization_synth.rpt -pb memory_01_utilization_synth.pb }
