# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/project_playlist/project_playlist.cache/wt [current_project]
set_property parent.project_path H:/project_playlist/project_playlist.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  H:/project_playlist/project_playlist.srcs/sources_1/new/playlistmemory.vhd
  H:/project_playlist/project_playlist.srcs/sources_1/new/playlistaddrcounter.vhd
  H:/project_playlist/project_playlist.srcs/sources_1/new/playlistcounter.vhd
  {H:/New folder/decoder1.vhd}
  {H:/New folder/addrcount1.vhd}
  {H:/New folder/ratecount3.vhd}
  {H:/New folder/memory12.vhd}
  {H:/New folder/volume11.vhd}
  {H:/New folder/pdm2.vhd}
  {H:/New folder/dds_top1.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{H:/New folder/constraintsssss1.xdc}}
set_property used_in_implementation false [get_files {{H:/New folder/constraintsssss1.xdc}}]


synth_design -top playlist -part xc7a100tcsg324-1


write_checkpoint -force -noxdef playlist.dcp

catch { report_utilization -file playlist_utilization_synth.rpt -pb playlist_utilization_synth.pb }
