# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {V:/EECS 700-FPGA/Hw/project_romext/project_romext.cache/wt} [current_project]
set_property parent.project_path {V:/EECS 700-FPGA/Hw/project_romext/project_romext.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {{V:/EECS 700-FPGA/Hw/project_romext/project_romext.srcs/sources_1/new/sourcefilee.v}}
synth_design -top rams_init_file -part xc7a100tcsg324-1
write_checkpoint -noxdef rams_init_file.dcp
catch { report_utilization -file rams_init_file_utilization_synth.rpt -pb rams_init_file_utilization_synth.pb }
