# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/Xilinxprojects/project_knightetest/project_knightetest.cache/wt [current_project]
set_property parent.project_path H:/Xilinxprojects/project_knightetest/project_knightetest.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet H:/Xilinxprojects/project_uartcontrol/ngc/uart_tx.dcp
set_property used_in_implementation false [get_files H:/Xilinxprojects/project_uartcontrol/ngc/uart_tx.dcp]
read_vhdl -library xil_defaultlib {
  H:/Xilinxprojects/project_knightetest/project_knightetest.srcs/sources_1/new/counterr.vhd
  H:/Xilinxprojects/project_knightetest/project_knightetest.srcs/sources_1/new/rom.vhd
  H:/Xilinxprojects/project_knightetest/project_knightetest.srcs/sources_1/new/knioght.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc H:/Xilinxprojects/project_knightetest/project_knightetest.srcs/constrs_1/new/constaraintsd.xdc
set_property used_in_implementation false [get_files H:/Xilinxprojects/project_knightetest/project_knightetest.srcs/constrs_1/new/constaraintsd.xdc]

read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]

synth_design -top knight_rider -part xc7a100tcsg324-1


write_checkpoint -force -noxdef knight_rider.dcp

catch { report_utilization -file knight_rider_utilization_synth.rpt -pb knight_rider_utilization_synth.pb }
