# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/project_awgv3/project_awgv3.cache/wt [current_project]
set_property parent.project_path H:/project_awgv3/project_awgv3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  H:/Backup/project_awg_v2/project_2.srcs/sources_1/new/addrcounter.vhd
  H:/Backup/project_awg_v2/project_2.srcs/sources_1/new/runmodule.vhd
  H:/Backup/project_awg_v2/project_2.srcs/sources_1/new/pdm.vhd
  H:/Backup/project_awg_v2/project_2.srcs/sources_1/new/counter4.vhd
  H:/Backup/project_awg_v2/project_2.srcs/sources_1/new/addrcounterreal.vhd
  H:/Backup/project_awg_v2/project_2.srcs/sources_1/new/volume.vhd
  H:/Backup/project_awg_v2/project_2.srcs/sources_1/new/knightrider.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc H:/Backup/project_awg_v2/project_2.srcs/constrs_1/new/constraintsssss.xdc
set_property used_in_implementation false [get_files H:/Backup/project_awg_v2/project_2.srcs/constrs_1/new/constraintsssss.xdc]


synth_design -top awg -part xc7a100tcsg324-1


write_checkpoint -force -noxdef awg.dcp

catch { report_utilization -file awg_utilization_synth.rpt -pb awg_utilization_synth.pb }
