# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {V:/EECS 700-FPGA/prj1/project_2/project_2.cache/wt} [current_project]
set_property parent.project_path {V:/EECS 700-FPGA/prj1/project_2/project_2.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  {V:/EECS 700-FPGA/prj1/project_2/project_2.srcs/sources_1/new/pdm.vhd}
  {V:/EECS 700-FPGA/prj1/project_2/project_2.srcs/sources_1/new/counter4.vhd}
  {V:/EECS 700-FPGA/prj1/project_2/project_2.srcs/sources_1/new/volume.vhd}
  {V:/EECS 700-FPGA/prj1/project_2/project_2.srcs/sources_1/new/runmodule.vhd}
  {V:/EECS 700-FPGA/prj1/project_2/project_2.srcs/sources_1/new/addrcounterreal.vhd}
  {V:/EECS 700-FPGA/prj1/project_2/project_2.srcs/sources_1/new/addrcounter.vhd}
  {V:/EECS 700-FPGA/prj1/project_2/project_2.srcs/sources_1/new/knightrider.vhd}
}
read_xdc {{V:/EECS 700-FPGA/prj1/project_2/project_2.srcs/constrs_1/new/constr.xdc}}
set_property used_in_implementation false [get_files {{V:/EECS 700-FPGA/prj1/project_2/project_2.srcs/constrs_1/new/constr.xdc}}]

synth_design -top awg -part xc7a100tcsg324-1
write_checkpoint -noxdef awg.dcp
catch { report_utilization -file awg_utilization_synth.rpt -pb awg_utilization_synth.pb }
