# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: v:/EECS 700-FPGA/New folder/project_1/project_1.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0.xci
# IP: The module: 'microblaze_mcs_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: v:/EECS 700-FPGA/New folder/project_1/project_1.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mcs_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: v:/EECS 700-FPGA/New folder/project_1/project_1.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mcs_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: v:/EECS 700-FPGA/New folder/project_1/project_1.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mcs_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: v:/EECS 700-FPGA/New folder/project_1/project_1.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0.xci
# IP: The module: 'microblaze_mcs_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: v:/EECS 700-FPGA/New folder/project_1/project_1.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mcs_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: v:/EECS 700-FPGA/New folder/project_1/project_1.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mcs_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: v:/EECS 700-FPGA/New folder/project_1/project_1.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mcs_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
