# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {V:/EECS 700-FPGA/New folder/project_1/project_1.cache/wt} [current_project]
set_property parent.project_path {V:/EECS 700-FPGA/New folder/project_1/project_1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip {{v:/EECS 700-FPGA/New folder/project_1/project_1.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0.xci}}
set_property is_locked true [get_files {{v:/EECS 700-FPGA/New folder/project_1/project_1.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0.xci}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top microblaze_mcs_0 -part xc7a100tcsg324-1 -mode out_of_context
rename_ref -prefix_all microblaze_mcs_0_
write_checkpoint -noxdef microblaze_mcs_0.dcp
catch { report_utilization -file microblaze_mcs_0_utilization_synth.rpt -pb microblaze_mcs_0_utilization_synth.pb }
if { [catch {
  file copy -force {V:/EECS 700-FPGA/New folder/project_1/project_1.runs/microblaze_mcs_0_synth_1/microblaze_mcs_0.dcp} {v:/EECS 700-FPGA/New folder/project_1/project_1.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0.dcp}
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub {v:/EECS 700-FPGA/New folder/project_1/project_1.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_stub.v}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub {v:/EECS 700-FPGA/New folder/project_1/project_1.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_stub.vhdl}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim {v:/EECS 700-FPGA/New folder/project_1/project_1.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_funcsim.v}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim {v:/EECS 700-FPGA/New folder/project_1/project_1.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_funcsim.vhdl}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
