# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr.xdc

# IP: ip/dsp48e1_prim/dsp48e1_prim.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsp48e1_prim || ORIG_REF_NAME==dsp48e1_prim}]
