# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/Xilinxprojects/project_linearinterpolation/project_linearinterpolation.cache/wt [current_project]
set_property parent.project_path H:/Xilinxprojects/project_linearinterpolation/project_linearinterpolation.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  H:/Xilinxprojects/project_linearinterpolation/project_linearinterpolation.srcs/sources_1/new/dff.vhd
  H:/Xilinxprojects/project_linearinterpolation/project_linearinterpolation.srcs/sources_1/new/interpolation.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top firfilter_5tap -part xc7a100tcsg324-1


write_checkpoint -force -noxdef firfilter_5tap.dcp

catch { report_utilization -file firfilter_5tap_utilization_synth.rpt -pb firfilter_5tap_utilization_synth.pb }
