# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {1}  -id {[BD 41-1306]}  -suppress 
set_msg_config  -ruleid {2}  -id {[BD 41-1271]}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/project_dft/project_dft.cache/wt [current_project]
set_property parent.project_path H:/project_dft/project_dft.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0.dcp
set_property used_in_implementation false [get_files h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0.dcp]
read_vhdl -library xil_defaultlib {
  H:/project_dft/project_dft.srcs/sources_1/new/dft.vhd
  H:/project_dft/project_dft.srcs/sources_1/new/memory.vhd
  H:/project_dft/project_dft.srcs/sources_1/new/mcs_dft.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc H:/project_dft/project_dft.srcs/constrs_1/new/constt.xdc
set_property used_in_implementation false [get_files H:/project_dft/project_dft.srcs/constrs_1/new/constt.xdc]


synth_design -top mcs_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef mcs_top.dcp

catch { report_utilization -file mcs_top_utilization_synth.rpt -pb mcs_top_utilization_synth.pb }
