# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0.xci
# IP: The module: 'microblaze_mcs_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/bd_0/bd_fc5c_0.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_0 || ORIG_REF_NAME==bd_fc5c_0}]

# IP: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_0_microblaze_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_0_microblaze_I_0 || ORIG_REF_NAME==bd_fc5c_0_microblaze_I_0}]

# IP: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_0_rst_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_0_rst_0_0 || ORIG_REF_NAME==bd_fc5c_0_rst_0_0}]

# IP: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_2/bd_fc5c_0_ilmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_0_ilmb_0 || ORIG_REF_NAME==bd_fc5c_0_ilmb_0}]

# IP: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_3/bd_fc5c_0_dlmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_0_dlmb_0 || ORIG_REF_NAME==bd_fc5c_0_dlmb_0}]

# IP: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_4/bd_fc5c_0_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_0_dlmb_cntlr_0 || ORIG_REF_NAME==bd_fc5c_0_dlmb_cntlr_0}]

# IP: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_5/bd_fc5c_0_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_0_ilmb_cntlr_0 || ORIG_REF_NAME==bd_fc5c_0_ilmb_cntlr_0}]

# IP: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_6/bd_fc5c_0_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_0_lmb_bram_I_0 || ORIG_REF_NAME==bd_fc5c_0_lmb_bram_I_0}]

# IP: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_7/bd_fc5c_0_iomodule_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_0_iomodule_0_0 || ORIG_REF_NAME==bd_fc5c_0_iomodule_0_0}]

# XDC: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/bd_0/bd_fc5c_0_ooc.xdc

# XDC: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mcs_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mcs_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0.xci
# IP: The module: 'microblaze_mcs_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/bd_0/bd_fc5c_0.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_0 || ORIG_REF_NAME==bd_fc5c_0}]

# IP: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_0_microblaze_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_0_microblaze_I_0 || ORIG_REF_NAME==bd_fc5c_0_microblaze_I_0}]

# IP: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_0_rst_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_0_rst_0_0 || ORIG_REF_NAME==bd_fc5c_0_rst_0_0}]

# IP: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_2/bd_fc5c_0_ilmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_0_ilmb_0 || ORIG_REF_NAME==bd_fc5c_0_ilmb_0}]

# IP: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_3/bd_fc5c_0_dlmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_0_dlmb_0 || ORIG_REF_NAME==bd_fc5c_0_dlmb_0}]

# IP: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_4/bd_fc5c_0_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_0_dlmb_cntlr_0 || ORIG_REF_NAME==bd_fc5c_0_dlmb_cntlr_0}]

# IP: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_5/bd_fc5c_0_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_0_ilmb_cntlr_0 || ORIG_REF_NAME==bd_fc5c_0_ilmb_cntlr_0}]

# IP: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_6/bd_fc5c_0_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_0_lmb_bram_I_0 || ORIG_REF_NAME==bd_fc5c_0_lmb_bram_I_0}]

# IP: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_7/bd_fc5c_0_iomodule_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_0_iomodule_0_0 || ORIG_REF_NAME==bd_fc5c_0_iomodule_0_0}]

# XDC: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/bd_0/bd_fc5c_0_ooc.xdc

# XDC: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mcs_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: h:/project_dft/project_dft.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mcs_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
