# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/Xilinxprojects/project_counterfinal/project_counterfinal.cache/wt [current_project]
set_property parent.project_path H:/Xilinxprojects/project_counterfinal/project_counterfinal.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib H:/Xilinxprojects/project_counterfinal/project_counterfinal.srcs/sources_1/new/counter_sourcef.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc H:/Xilinxprojects/project_counterfinal/project_counterfinal.srcs/constrs_1/new/constr.xdc
set_property used_in_implementation false [get_files H:/Xilinxprojects/project_counterfinal/project_counterfinal.srcs/constrs_1/new/constr.xdc]


synth_design -top ratecounter_source -part xc7a100tcsg324-1


write_checkpoint -force -noxdef ratecounter_source.dcp

catch { report_utilization -file ratecounter_source_utilization_synth.rpt -pb ratecounter_source_utilization_synth.pb }
