# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/Xilinxprojects/project_2/project_2.cache/wt [current_project]
set_property parent.project_path H:/Xilinxprojects/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet H:/Xilinxprojects/project_uartcontrol/ngc/uart_rx.dcp
set_property used_in_implementation false [get_files H:/Xilinxprojects/project_uartcontrol/ngc/uart_rx.dcp]
add_files -quiet H:/Xilinxprojects/project_uartcontrol/ngc/uart_tx.dcp
set_property used_in_implementation false [get_files H:/Xilinxprojects/project_uartcontrol/ngc/uart_tx.dcp]
read_verilog -library xil_defaultlib {
  H:/Xilinxprojects/project_uartcontrol/ngc/uart_tx.v
  H:/Xilinxprojects/project_uartcontrol/ngc/uart_rx.v
  H:/Xilinxprojects/project_uartcontrol/test/uart_loop.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{H:/EECS 700/Nexys4_Master.xdc}}
set_property used_in_implementation false [get_files {{H:/EECS 700/Nexys4_Master.xdc}}]

read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]

synth_design -top uart_loop -part xc7a100tcsg324-1


write_checkpoint -force -noxdef uart_loop.dcp

catch { report_utilization -file uart_loop_utilization_synth.rpt -pb uart_loop_utilization_synth.pb }
