# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/Xilinxprojects/project_meminitialize/project_meminitialize.cache/wt [current_project]
set_property parent.project_path H:/Xilinxprojects/project_meminitialize/project_meminitialize.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib H:/Xilinxprojects/drive-download-20170224T145020Z-001/rom_vhd_mif.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top memory_01 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef memory_01.dcp

catch { report_utilization -file memory_01_utilization_synth.rpt -pb memory_01_utilization_synth.pb }
